### ISSUE TITLE
Upgrade to latest thrift version

### ISSUE THREAD

**Issue by ctavan** [simplereach/node-thrift#2]
I think now that the npm module over at https://github.com/wadey/node-thrift will no longer be maintained we should upgrade the thrift-dependency to the latest SVN version from http://svn.apache.org/viewvc/thrift/trunk/lib/nodejs/

A couple of issues have been fixed there (like https://issues.apache.org/jira/browse/THRIFT-1277) which would remove the need of patching the thrift-generated js-files in the cassandra driver.

@devdazed: The history of this repo since it has been forked looks a bit chaotic to me so I'm not a 100% sure which fixes were introduced by you but maybe we can manage to get these fixes applied upstream?

I'm also willing to help in upgrading the npm-module. Maybe we can get the maintainer of the node-thrift module to hand over the name for this one...

**Comment by devdazed** [comment]
I agree, there has been quite a few changes since the fork.  And there is a couple other issues that need to be taken care of as well.  The main concern I have is that a lot of the fixes I have made to this repo were ser-de issues and providing buffer support as well as fixing a race condition and global variable leaks.  all of the changes were relatively small, so if we can get them working into the main repo, then i dont see why we wont be able to track the svn version and provide an npm module from github.

**Comment by devdazed** [comment]
additionally, that version is for thrift 0.9.0 which we shouldnt be using. we need the 0.7.x version so, we need to ensure they are maintaining that as well.
